[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000

[parachains.collator]
name = "dave"
ws_port = 8844
command = "polkadot-parachain"

[[parachains]]
id = 2000

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "parachain-example-node"
